### ISSUE TITLE
Remediations prority should be handle in the bouncer configuration directly

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/php-cs-bouncer#54]
Hello,

From what i see [here](https://github.com/crowdsecurity/php-cs-bouncer/blob/main/src/Constants.php#L47), remediations priorities are hardcoded in the bouncer library directly. I think it would be better to handle this directly in the bouncer configurations.

For example for the php bouncer, i would like to configure this in https://github.com/crowdsecurity/cs-php-bouncer/blob/main/settings.example.php directly.

**Comment by mobula9** [comment]
I closed this ticket as there is already a better way to handle initial need.
